apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: widgetario/web:21.03
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: web-config-volume
          mountPath: /app/secrets
      volumes:
      - name: web-config-volume
        configMap:
          name: web-config
